---
name: "Newsletters"
guid: "60f478ab-2dd6-4ea0-af10-04d033f75979"
imageUrl: "https://raw.githubusercontent.com/Sanidhya30/Jellyfin-Newsletter/master/images/logo.png"
version: "1.8.0.1"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Send newsletters for recently added/deleted/updated/upcoming media"
description: "This plugin populates a list of recently added/deleted/updated media and upcoming content (via Radarr/Sonarr), sends out the newsletter to configured clients(email, discord webhook, telegram & matrix)."
category: "General"
owner: "kirankumarraj94-eng"
artifacts:
  - "Jellyfin.Plugin.Newsletters.dll"
  - "SQLitePCL.pretty.dll"
  - "SixLabors.ImageSharp.dll"
  - "MailKit.dll"
  - "MimeKit.dll"
  - "BouncyCastle.Cryptography.dll"
changelog: |
  - Feature: Added configurable email From Name.
  - Improvement: Email messages can now display a friendly sender name.
